//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

TTMATSystemService_getMailboxTTMAT_args = function(args) {
  this.user = null;
  this.date = null;
  if (args) {
    if (args.user !== undefined) {
      this.user = args.user;
    }
    if (args.date !== undefined) {
      this.date = args.date;
    }
  }
};
TTMATSystemService_getMailboxTTMAT_args.prototype = {};
TTMATSystemService_getMailboxTTMAT_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.user = new User();
        this.user.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.date = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TTMATSystemService_getMailboxTTMAT_args.prototype.write = function(output) {
  output.writeStructBegin('TTMATSystemService_getMailboxTTMAT_args');
  if (this.user !== null && this.user !== undefined) {
    output.writeFieldBegin('user', Thrift.Type.STRUCT, 1);
    this.user.write(output);
    output.writeFieldEnd();
  }
  if (this.date !== null && this.date !== undefined) {
    output.writeFieldBegin('date', Thrift.Type.STRING, 2);
    output.writeString(this.date);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TTMATSystemService_getMailboxTTMAT_result = function(args) {
  this.success = null;
  this.ouch = null;
  if (args instanceof InvalidOperation) {
    this.ouch = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.ouch !== undefined) {
      this.ouch = args.ouch;
    }
  }
};
TTMATSystemService_getMailboxTTMAT_result.prototype = {};
TTMATSystemService_getMailboxTTMAT_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new MailboxTTMAT();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ouch = new InvalidOperation();
        this.ouch.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TTMATSystemService_getMailboxTTMAT_result.prototype.write = function(output) {
  output.writeStructBegin('TTMATSystemService_getMailboxTTMAT_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.ouch !== null && this.ouch !== undefined) {
    output.writeFieldBegin('ouch', Thrift.Type.STRUCT, 1);
    this.ouch.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TTMATSystemServiceClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
TTMATSystemServiceClient.prototype = {};
TTMATSystemServiceClient.prototype.getMailboxTTMAT = function(user, date) {
  this.send_getMailboxTTMAT(user, date);
  return this.recv_getMailboxTTMAT();
};

TTMATSystemServiceClient.prototype.send_getMailboxTTMAT = function(user, date) {
  this.output.writeMessageBegin('getMailboxTTMAT', Thrift.MessageType.CALL, this.seqid);
  var args = new TTMATSystemService_getMailboxTTMAT_args();
  args.user = user;
  args.date = date;
  args.write(this.output);
  this.output.writeMessageEnd();
  return this.output.getTransport().flush();
};

TTMATSystemServiceClient.prototype.recv_getMailboxTTMAT = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new TTMATSystemService_getMailboxTTMAT_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.ouch) {
    throw result.ouch;
  }
  if (null !== result.success) {
    return result.success;
  }
  throw 'getMailboxTTMAT failed: unknown result';
};
