/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "authenication_constants.h"

namespace authentication {

const authenicationConstants g_authenication_constants;

authenicationConstants::authenicationConstants() {
}

} // namespace

