/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef authenication_CONSTANTS_H
#define authenication_CONSTANTS_H

#include "authenication_types.h"

namespace authentication {

class authenicationConstants {
 public:
  authenicationConstants();

};

extern const authenicationConstants g_authenication_constants;

} // namespace

#endif
