/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ttmat_internal_constants.h"

namespace ttmat {

const ttmat_internalConstants g_ttmat_internal_constants;

ttmat_internalConstants::ttmat_internalConstants() {
}

} // namespace

