/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ttmat_internal_CONSTANTS_H
#define ttmat_internal_CONSTANTS_H

#include "ttmat_internal_types.h"

namespace ttmat {

class ttmat_internalConstants {
 public:
  ttmat_internalConstants();

};

extern const ttmat_internalConstants g_ttmat_internal_constants;

} // namespace

#endif
